# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 柯城区2018“一村万树”布局图
email: Fu_sion@live.com
description: > # this means to ignore newlines until "baseurl:"
  这是一个测试页面！
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fdson.com" # the base hostname & protocol for your site
twitter_username: Fu_sion
github_username:  SionFu

# Build settings
markdown: kramdown

# 修改标题链接 为短链接
permalink: '/:title.html'

# 添加代码高亮样式
highlighter: rouge
